### ISSUE TITLE
Build Error: Namespace and Member Issues in TypeScript Compilation

### ISSUE THREAD

**Issue by jsilets** [citrineos/citrineos-core#26] opened 2023-12-28 15:54 UTC
Issue Description:
During the installation and build process of the citrineos-core project, TypeScript compilation errors are met, specifically related to @types/glob and minimatch. The process fails while executing npm install in the 00_Base directory. This is during execution of ./unix-init-install-all.sh in the 50_Server directory.

Actual Behavior:
The following TypeScript errors are met:

```
node_modules/@types/glob/index.d.ts:29:42 - error TS2694: Namespace '"/path/to/node_modules/minimatch/dist/cjs/index"' has no exported member 'IOptions'.
node_modules/@types/glob/index.d.ts:74:30 - error TS2724: '"/path/to/node_modules/minimatch/dist/cjs/index"' has no exported member named 'IMinimatch'. Did you mean 'Minimatch'?
```

Additional Information:
Node version: v20.2.0
Potential fix: [https://stackoverflow.com/questions/75890950/node-modules-minimatch-dist-cjs-index-has-no-exported-member-ioptions](url)

**Comment by thanaParis** [comment] 2023-12-29 19:27
Thank you for opening this and linking the stackoverflow thread! That was very helpful in diagnosing the root cause. I've fixed it in this PR: https://github.com/citrineos/citrineos-core/pull/30 .
I will close this issue once that PR merges and main is tagged with v0.2.1. Please let me know if there's any issues building 0.2.1.

**Comment by thanaParis** [comment] 2023-12-30 18:28
Closing this now. Please re-open it if you run into this build issue again.

**Closed** 2023-12-30 18:28 UTC
